### ISSUE TITLE
GenerateYoloxProposals - Magic number 5

### ISSUE THREAD

**Issue by derek-knox** [cj-mills/icevision-openvino-unity-tutorial#2]
@cj-mills Normally I'd link to the LOC but since the [code in question is a Notebook](https://github.com/cj-mills/icevision-openvino-unity-tutorial/blob/main/notebooks/Icevision-YOLOX-to-OpenVINO-Tutorial-HaGRID-Kaggle.ipynb) it wasn't obvious. As a result I took a screenshot which is below. My questions are:

1. What is the magic number `5` highlighted in the `num_classes` assignment?
2. Is this the same number `5` in the `box_cls_score` assignment or is that coincidence?
    - Unless I'm missing something obvious it's likely worth assigning to a named variable(s) to remove ambiguity.
3. Is there a reason the `struct Object` isn't called `struct Proposal`? That's how I'm interpreting the notebook code but maybe there is a good reason for the name to be so generic?

Anyway, great tutorials. I'm just looking for confirmation on some confusing aspects.

![image](https://user-images.githubusercontent.com/21041937/229941052-9d2ca26e-ba29-4aad-aeef-e3af79988ec8.png)

**Comment by cj-mills** [comment]
Hi @derek-knox ,
The magic number 5 refers to the number of values the model predicts for each bounding box, regardless of the number of object classes. And it is indeed the same value used in the `box_cls_score` variable assignment.
1. Bounding box center x-coordinate
2. Bounding box center y-coordinate
3. Bounding box width
4. Bounding box height
5. Objectness score

![GenerateYoloxProposals-magic-number-5](https://user-images.githubusercontent.com/9126128/229945936-8f2f59f2-faf3-41e8-9275-0c81f245f480.png)


I agree that I should have used a variable for it, and I am now. I ended up naming it `NumBBoxFields` in my Barracuda implementation (not on GitHub yet).

```c#
/// <summary>
/// YOLOXObjectDetector is a class that extends BarracudaModelRunner for object detection using the YOLOX model.
/// It handles model execution, processes the output, and generates bounding boxes with corresponding labels and colors.
/// The class supports various worker types, including PixelShader and ComputePrecompiled, as well as Async GPU Readback.
/// </summary>
public class YOLOXObjectDetector : BarracudaModelRunner
{
    // Output Processing configuration and variables
    [Header("Output Processing")]
    // JSON file containing the color map for bounding boxes
    [SerializeField, Tooltip("JSON file with bounding box colormaps")]
    private TextAsset colormapFile;

    // Indicates if the system supports asynchronous GPU readback
    private bool supportsAsyncGPUReadback = false;

    // Stride values used by the YOLOX model
    private static readonly int[] Strides = { 8, 16, 32 };

    // Number of fields in each bounding box
    private const int NumBBoxFields = 5;
```

The struct Object name is a legacy name from when I first experimented with making a plugin for the YOLOX model for Unity. I did not spend much time thinking about the name for it as I was already well over my time budget for this tutorial. 

I currently name the struct `BBox2D`.
```c#
/// <summary>
/// A struct that represents a 2D bounding box.
/// </summary>
public struct BBox2D
{
    public float x0;
    public float y0;
    public float width;
    public float height;
    public int index;
    public float prob;

    /// <summary>
    /// Initializes a new instance of the BBox2D struct.
    /// </summary>
    /// <param name="x0">The x-coordinate of the top-left corner.</param>
    /// <param name="y0">The y-coordinate of the top-left corner.</param>
    /// <param name="width">The width of the bounding box.</param>
    /// <param name="height">The height of the bounding box.</param>
    /// <param name="index">The class index of the object.</param>
    /// <param name="prob">The probability of the object belonging to the given class.</param>
    public BBox2D(float x0, float y0, float width, float height, int index, float prob)
    {
        this.x0 = x0;
        this.y0 = y0;
        this.width = width;
        this.height = height;
        this.index = index;
        this.prob = prob;
    }
}
```

I'll probably refresh that tutorial a bit to give everything consistent names across the tutorials.

**Comment by derek-knox** [comment]
@cj-mills I totally get the time budget goals 😊 Thank you for the clarification!
